pages:
  - title: Home
    url: /
    template: basic-page
    files:
      - pages/home.md

  - title: Static Reference
    url: /reference
    template: doc-page
    files:
      - pages/reference.md
    sidemenu:
    - name: Term Definitions
      slug: reference
    - name: Field Types
    - name: Feed Files
    - name: File Requirements
    - name: Field Definitions
      children:
      - name: agency.txt
      - name: stops.txt
      - name: routes.txt
      - name: trips.txt
      - name: stop_times.txt
      - name: calendar.txt
      - name: calendar_dates.txt
      - name: fare_attributes.txt
      - name: fare_rules.txt
      - name: shapes.txt
      - name: frequencies.txt
      - name: transfers.txt
      - name: feed_info.txt

  - title: Realtime Reference
    url: /realtime
    template: doc-page
    files:
      - pages/realtime.md
    sidemenu:
    - name: Feed Message
      anchor: realtime/#message-feedmessage
      slug: reference
      children:
      - name: Feed Header
        children:
        - name: Incrementality
      - name: Feed Entity
        children:
        - name:	Trip Update
          children:
            - Trip Descriptor
            - Vehicle Descriptor
            - Stop Time Update
        - name: Vehicle Position
          children:
            - Trip Descriptor
            - Vehicle Descriptor
            - Position
            - Vehicle Stop Status
            - Congestion Level
            - Occupancy Status
        - name: Alert
          children:
            - Time Range
            - Entity Selector
            - Cause Effect
            - Translated String

  - title: Best Practices
    url: /best-practices
    template: doc-page
    sidemenu:
    - name: Introduction
      # slug: about
      anchor: best-practices/
    - name: Dataset Publishing & General Practices
      slug: publishing
      anchor: best-practices/
    - name: Recommendations Organized by File
      slug: all-files
      anchor: best-practices/
      children :
        - name: All Files
          file: about.md
        - name: agency.txt
          slug: agency
        - name: stops.txt
          slug: stops
        - name: routes.txt
          slug: routes
        - name: trips.txt
          slug: trips
        - name: stop_times.txt
          slug: stop_times
        - name: calendar.txt
          slug: calendar
        - name: calendar_dates.txt
          slug: calendar_dates
        - name: fare_attributes.txt
          slug: fare_attributes
        - name: fare_rules.txt
          slug: fare_rules
        - name: shapes.txt
          slug: shapes
        - name: frequencies.txt
          slug: frequencies
        - name: transfers.txt
          slug: transfers
        - name: feed_info.txt
          slug: feed_info
    - name: Recommendations Organized by Case
      slug: null
      anchor: best-practices/
      children:
        - name: Loop Routes
          slug: loop-routes
        - name: Lasso Routes
          slug: lasso-routes
        - name: Branches
          slug: branches
    - name: About This Document
      slug: about
      anchor: best-practices/

  - title: Examples
    url: /examples
    template: basic-page
    files:
      - pages/examples.md
    sidemenu:
        - name: Getting Started
          slug: getting-started
          anchor: null
          children:
            - name: Overview
              slug: introduction.md
            - name: Installation
              slug: installation.md
            - name: Creating your site
              slug: creating-site.md
            - name: Publishing your site
              slug: publishing.md

  - title: Testing
    url: /testing
    template: basic-page

  - title: Getting Started
    url: /getting-started
    template: basic-page

  - title: GTFS Background
    url: /background
    template: basic-page
