pages:
  - title: Home
    url: /
    template: basic-page
    files:
      - pages/home.md

  - title: Static Reference
    url: /reference
    template: doc-page
    files:
      - pages/reference.md
    toc: /ref-contents/

  - title: Realtime Reference
    url: /realtime
    template: doc-page
    files:
      - pages/realtime.md
    toc: /realtime-contents/

  - title: Best Practices
    url: /best-practices
    template: doc-page
    files:
      - agency.md
      - stops.md
      - routes.md
    toc: /best-practices-contents/

  - title: Examples
    url: /examples
    template: basic-page
    files:
      - pages/examples.md

  - title: Testing
    url: /testing
    template: basic-page

  - title: Getting Started
    url: /getting-started
    template: basic-page

  - title: GTFS Background
    url: /background
    template: basic-page
