version: 2
jobs:
  build:
    steps:
      - checkout
      - run: git clone git@github.com:rocky-mountain-institute/gtfs-best-practices.git _best-practices/
      - run: git clone git@github.com:rocky-mountain-institute/gtfs-reference.git _reference/
      - run: bundle exec jekyll build

