version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: npm install
      - run:
          name: Fetch reference source repos
          command: git clone https://github.com/google/transit src/pages/reference
      - run:
          name: Fetch best practices repo
          command: git clone --single-branch -b docsv2 https://github.com/MobilityData/gtfs-best-practices src/pages/best-practices
      - run: npm run build
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync public s3://gtfs.org/ --delete
            fi
